# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nftool < Formula
  desc "A suite of tools for NFT generative art."
  homepage "https://github.com/alephao/nftool"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alephao/nftool/releases/download/v0.1.0/nftool_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b40ce9bcaddec6a93b6971bb9a0236bfe7ee4dde65de4b6701ccb9a63f6119b1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/alephao/nftool/releases/download/v0.1.0/nftool_0.1.0_Darwin_arm64.tar.gz"
      sha256 "e493304bb91dcdc16ad4624d92c5fcbbeb572cb487571ef31de92e6f86ca45c2"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alephao/nftool/releases/download/v0.1.0/nftool_0.1.0_Linux_arm64.tar.gz"
      sha256 "9526b7149cfb15acaabe73cb5cca84531b745a1b3b5c33f02cd48acbdacc692e"
    end
    if Hardware::CPU.intel?
      url "https://github.com/alephao/nftool/releases/download/v0.1.0/nftool_0.1.0_Linux_x86_64.tar.gz"
      sha256 "170b5547de5cd5a98d0be77f014d2971c6b5795778824db09ffd5319c519015a"
    end
  end

  def install
    bin.install "nftool"
  end
end
