# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nftool < Formula
  desc "A suite of tools for NFT generative art."
  homepage "https://github.com/alephao/nftool"
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alephao/nftool/releases/download/v0.2.0/nftool_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "2d3d6a0f5e9434f39b1d5a47a7e387d2f7809db9297c7926bacef46502b7d9e3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/alephao/nftool/releases/download/v0.2.0/nftool_0.2.0_Darwin_arm64.tar.gz"
      sha256 "81eb1b2b34fa12ad3cf5f16db8c4eb884cfa12cc504625a378a828cadde8e487"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alephao/nftool/releases/download/v0.2.0/nftool_0.2.0_Linux_arm64.tar.gz"
      sha256 "bdb84a126551129359a3d59cdf92e2b8201a34813b69e9772866815b3a6fea8b"
    end
    if Hardware::CPU.intel?
      url "https://github.com/alephao/nftool/releases/download/v0.2.0/nftool_0.2.0_Linux_x86_64.tar.gz"
      sha256 "2dfd53e5520e2f61528370b19bb9710675dd6e5427d2f6f4b5ab9726fce2c3ac"
    end
  end

  def install
    bin.install "nftool"
  end
end
